### ISSUE TITLE
When I use this mod I can't see names

### ISSUE THREAD

**Issue by SubwaySurfers69** [wisp-forest/owo-lib#90] opened 2023-02-02 08:21 UTC
When I use this mod I can't see the names of any mobs with {CustomNameVisible:1b} and I can't find a config anywhere.
If this isn't an issue please help, I want to use a mod that requires this but I also want to be able to see names of entities.

**Comment by Noaaan** [comment] 2023-02-02 08:22
This is potentially a duplicate of https://github.com/wisp-forest/owo-lib/issues/84, as it was fixed in owo-lib 0.10.2

**Comment by SubwaySurfers69** [comment] 2023-02-02 08:24
ohh I'll install this manually because the mod was installing it and maybe it's not installing the latest version

**Comment by SubwaySurfers69** [comment] 2023-02-02 08:25
I can see item frames though

**Comment by SubwaySurfers69** [comment] 2023-02-02 08:29
Yep that worked thank you for helping Imma close this.

**Closed as completed** 2023-02-02 08:29 UTC
