### ISSUE TITLE
owo-ui error, no UI with id owo:config was found

### ISSUE THREAD

**Issue by stefano-ferraro** [wisp-forest/owo-lib#165] opened 2023-08-13 12:44 UTC
Everytime i log into the game this message appears in ModMenu and i don't know what's wrong, but this doesn't let me use resource packs and reloading textures, anyone knows how to fix it?

![Screenshot 2023-08-09 175728](https://github.com/wisp-forest/owo-lib/assets/142156530/504d6509-3dbf-4931-a277-79b9256b9c17)

**Comment by gliscowo** [comment] 2023-08-13 12:48
This is a duplicate of #61, however your case could still be relevant. Do you certainly have a setup which reproduces this error 100% of the time? If so (and I mean, do this either way), please send us your `latest.log` to further diagnose the issue.

This, among other things, contains your mod list so we can maybe look into getting the error fixed if we can actually reliably reproduce it

Cheers

**Comment by stefano-ferraro** [comment] 2023-08-13 12:51
[latest.log](https://github.com/wisp-forest/owo-lib/files/12329543/latest.log)

the error happens everytime

i discovered this error yesterday while trying to stay afk, so i used F3 + T and after loading my world crashed

**Comment by Noaaan** [comment] 2023-08-14 21:46
As discussed in Discord, this is an incompatibility issue with Axiom and Architectury, which breaks loading resources in general. As of Axiom `b1.0.0` and above, this issue has been fixed. Please update to this version.

**Closed as completed** 2023-08-14 21:49 UTC
Labels: status: confirmed, type: compatibility
