### ISSUE TITLE
[1.20.1] Screen is null Crash when loading up singleplayer menu

### ISSUE THREAD

**Issue by ConqAra** [wisp-forest/owo-lib#210] opened 2024-01-03 03:16 UTC
Getting a really weird crash every time I load up the singleplayer menu in my modpack. I tried removing reimagined menu, deathlog, updating fancymenu... I just can't get owolib to stop complaining. Any ideas on what could be incompatible with it? I have latest version of fabric api and fabric loader. 

Log: [https://mclo.gs/cBVhdJ6](https://mclo.gs/cBVhdJ6)

**Comment by gliscowo** [comment] 2024-01-05 14:07
Have you tried removing FancyMenu entirely? As far as I remember, this is a problem both in incompatibility with and caused by FancyMenu that we can do nothing about. The author said [here](https://github.com/wisp-forest/owo-lib/issues/133#issuecomment-1603482334) that they're working on a fix, I do not believe that is released yet though

Cheers

**Comment by BasiqueEvangelist** [comment] 2024-01-05 14:14
That incompatibility should have been fixed with https://modrinth.com/mod/fancymenu/version/2.14.10-1.20.1-fabric, which is listed as installed in the Crash Report :thinking:

**Comment by ConqAra** [comment] 2024-01-08 04:37
Yeah it was fancymenu again. When i removed fancymenu and its dependents it worked...

**Comment by gliscowo** [comment] 2024-01-16 00:06
Looking at how this appears to be another FancyMenu problem, I suggest you go report this to them once more - I'll be closing this issue as a duplicate of #133

Cheers

**Closed as not planned by gliscowo** 2024-01-16 00:06 UTC
Labels: status: wontfix, priority: normal, type: compatibility
