### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [wisp-forest/owo-lib#239] opened 2024-05-26 17:46 UTC
![$G6(7(~N3A7OU4~M(WR$ZK7](https://github.com/wisp-forest/owo-lib/assets/155424398/ac4c84b0-a1cb-4999-97d4-dbabfef1d177)

**Comment by gliscowo** [comment] 2024-07-04 20:52
Duplicate of #61, for which we currently don't know a solution

**Closed as not planned by gliscowo** 2024-07-04 20:52 UTC
