### ISSUE TITLE
[Server Crash] - Fabric 1.18.2 - CME - Feature Placement

### ISSUE THREAD

**Issue by xR4YM0ND** [wisp-forest/owo-lib#46] opened 2022-08-02 12:00 UTC
i tested it 2 times , 1 time with a new AE2 version and other outputs came through.

[Crash Report 1](https://gist.github.com/SpigotDE/a96aaaad621f6d9910eaffe7c8f1cba5)
[latest.log 1](https://gist.github.com/SpigotDE/6867a48c58d54d502a3202ef32fbdbce)

[Crash Report 2](https://gist.github.com/SpigotDE/c885b77b8b6a7de0216bd259996117a1)
[latest.log 2](https://gist.github.com/SpigotDE/b66b090e88bd024f00e5df369d53c729)

I could not connect to the server anymore. 

After disabling OWO Lib & Things Mod i can connect and no crash report comes

**Comment by ghost** [comment] 2022-08-03 05:51
Have you checked if it's actually owo-lib and not just Things?

**Comment by Noaaan** [comment] 2022-08-03 06:24
https://github.com/wisp-forest/things/issues/41

**Comment by gliscowo** [comment] 2022-08-09 00:06
This crash is almost certainly caused by Things and not owo, as such I'll go ahead and close this issue
Cheers

**Closed as not planned by gliscowo** 2022-08-09 00:06 UTC

**Comment by Bob74** [comment] 2022-10-11 23:42
@SpigotDE It certainly comes from Things.
This version should fix the issue: https://github.com/Bob74/things-1.18.2-fix

You need both:
- [things-0.2.19+1.18.jar](https://github.com/Bob74/things-1.18.2-fix/releases/download/0.2.19%2B1.18/things-0.2.19+1.18.jar)
- [owo-lib-0.7.3+1.18.jar](https://github.com/Bob74/owo-lib-1.18.2-fix/releases/download/0.7.3%2B1.18/owo-lib-0.7.3+1.18.jar)
