### ISSUE TITLE
Non [a-z0-9_.-] character in namespace of location: shaders/core/owo:spectrum.json

### ISSUE THREAD

**Issue by MADxingjin** [wisp-forest/owo-lib#122] opened 2023-04-01 15:36 UTC
# Version
 0.10.3+1.19.4
# What happened ? 
Crash on loading or joining any world. no log4j log written to disk.
BELOW ARE COPIED FROM MultiMC CONSOLE.

# Full Error MSG

[23:28:00] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[23:28:00] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[23:28:00] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[23:28:00] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[23:28:00] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[23:28:00] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[23:28:00] [Render thread/INFO]: Created: 64x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[23:28:00] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[23:28:00] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[23:28:01] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: shaders/core/owo:spectrum.json
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1174) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: shaders/core/owo:spectrum.json
	at net.minecraft.class_2960.method_45135(class_2960.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:124) ~[client-intermediary.jar:?]
	at io.wispforest.owo.shader.GlProgram.lambda$new$0(GlProgram.java:49) ~[owo-lib-0.10.3+1.19.4.jar:?]
	at net.minecraft.class_757.md3cf7a8$owo$lambda$loadAllTheShaders$0$2(class_757.java:8155) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.wispforest.owo.shader.GlProgram.forEachProgram(GlProgram.java:88) ~[owo-lib-0.10.3+1.19.4.jar:?]
	at net.minecraft.class_757.handler$ced000$owo$loadAllTheShaders(class_757.java:8155) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:499) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:437) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 20 more

## Modlist

[23:27:40] [main/INFO]: Loading 123 mods:
	- architectury 8.1.75
	- authme 6.0.0
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   \-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	- betterf3 6.0.0
	- blockmeter 1.9.1
	- blur 3.0.0
	   |-- midnightlib 1.2.1
	   \-- satin 1.11.0
	- bobby 4.0.5
	   |-- com_typesafe_config 1.4.2
	   |-- fabric-command-api-v2 2.2.4+ae0966bad8
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- chat_heads 0.10.9
	- chunksfadein 1.0.2-1.19.4
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- cloth-config 10.0.96
	   \-- cloth-basic-math 0.6.1
	- deathlog 0.3.2+1.19.4
	- debugify 1.19.4+1.0
	   \-- com_github_llamalad7_mixinextras 0.1.1
	- dynamicfps 2.2.0
	- emi 0.7.3+1.19.4
	- entityculling 1.6.2-mc1.19.4
	- fabric-api 0.76.0+1.19.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
	   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.25+f71b366ff4
	   |-- fabric-commands-v0 0.2.42+df3654b3f4
	   |-- fabric-containers-v0 0.1.52+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
	   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.16+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.25+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
	   |-- fabric-models-v0 0.3.29+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   |-- fabric-networking-v0 0.3.39+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
	   |-- fabric-particles-v1 1.0.22+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.1.2+a383ab97f4
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
	   |-- fabric-rendering-v0 1.1.40+df3654b3f4
	   |-- fabric-rendering-v1 2.1.0+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.8+75e98211f4
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
	- fabric-language-kotlin 1.9.3+kotlin.1.8.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- ferritecore 5.2.0
	- indium 1.0.15+mc1.19.4
	- inventoryprofilesnext 1.9.4
	- iris 1.5.2
	   |-- io_github_douira_glsl-transformer 2.0.0-pre9
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- isometric-renders 0.4.4+1.19.4
	   \-- worldmesher 0.3.0+1.19.3
	- jade 10.0.0
	- java 17
	- journeymap 5.9.4beta2
	   \-- journeymap-api-fabric 1.19.4-1.9-fabric-SNAPSHOT
	- krypton 0.2.2
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lambdynlights 2.3.0+1.19.4
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 4.2.0+1.19.4
	- libipn 2.0.4
	- make_bubbles_pop 0.1.1-1.19.4
	- minecraft 1.19.4
	- modmenu 6.1.0-rc.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   \-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	- morechathistory 1.1.1
	- moreculling 1.19.4-0.17.0
	   \-- conditional-mixin 0.3.2
	- mousetweaks 2.24
	- namepain 1.4.0
	- no-telemetry 1.7.0
	- nochatreports 1.19.4-v2.1.1
	- owo 0.10.3+1.19.4
	   \-- blue_endless_jankson 1.2.2
	- replaymod 1.19.4-2.6.12
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   \-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	- screenshotclipboard 1.0.9
	- sodium 0.4.10+build.24
	- tooltipfix 1.1.1-1.19.3
	- vanilla-notebook 2.2.0
	- yet-another-config-lib 2.3.1
---

**Comment by MADxingjin** [comment] 2023-04-01 15:51
Update:
unloaded Blur3.0 and it works as intended, pretty strange behavior, gotta check blur mod src.

**Comment by gliscowo** [comment] 2023-04-04 11:35
I'll be closing this, as it's in essence a duplicate of #120 
Cheers

**Closed as not planned by gliscowo** 2023-04-04 11:35 UTC
Labels: status: confirmed, type: compatibility
