### ISSUE TITLE
owo->@Inject::afterQuiltHook injection failed and crashed the game

### ISSUE THREAD

**Issue by vlad2305m** [wisp-forest/owo-lib#35] opened 2022-06-23 19:01 UTC
Can you make [afterQuiltHook](https://github.com/wisp-forest/owo-lib/blob/1.19/src/main/java/io/wispforest/owo/mixin/MinecraftClientMixin.java#L27) optional so that players without quilt don't crash?

(Source: https://github.com/vlad2305m/AkashicTomeOfToolsFabric/issues/6)

**Comment by gliscowo** [comment] 2022-06-23 19:03
This is in essence a duplicate of #34, the solution is explained there - basically user error with the mixin debug flags
Cheers

**Closed as completed by gliscowo** 2022-06-23 19:03 UTC
