### ISSUE TITLE
owo-lib 0.10.4 incompatibilities with Fancy menu

### ISSUE THREAD

**Issue by NantaArthur123** [wisp-forest/owo-lib#133] opened 2023-05-21 00:41 UTC
I'm playing in 1.19.4 Fabric modloader

How to reproduce:
1. Install latest mod of owo and Fancy menu.
2. Open multiplayer screen, go back
3. Open singleplayer screen, go back
4. Open option screen, go back
5. Press "Miscellaneous" from fancy menu option
6. Press "Open Connect Screen" from "Miscellaneous"

[crash-2023-05-21_07.32.06-client.txt](https://github.com/wisp-forest/owo-lib/files/11523427/crash-2023-05-21_07.32.06-client.txt)

**Comment by gliscowo** [comment] 2023-05-30 17:11
While I can in fact reproduce this issue, I find it highly unlikely to be caused by owo. As evidenced by the crash, FancyMenu is somehow causing the screen passed by Fabric API's render event to become `null`, which isn't a valid state and thus not something owo needs to handle gracefully - in fact, it demonstrates that FancyMenu is somehow broken.

If you'd like to see this fixed, I'd recommend you report it on the FancyMenu repository instead so the maintainer can look into what's causing this

I'll keep the issue open in the time being, although we won't be actively working on this
Cheers

**Comment by Keksuccino** [comment] 2023-06-23 00:45
Hi, dev of FancyMenu here!
This is indeed on FancyMenu's end and it will be fixed in the upcoming FancyMenu v3 (currently in development)!

**Closed as not planned** 2023-08-20 00:16 UTC
Labels: priority: low, status: confirmed, type: compatibility
