### ISSUE TITLE
owo-ui-error; No ui model with id:config

### ISSUE THREAD

**Issue by notIkibo** [wisp-forest/owo-lib#61] opened 2022-10-17 07:41 UTC
I guess everything works fine (?)
Though every time I open my MC modpack, I see this. Really every time. I couldn't find anything in the logs. 
![image](https://user-images.githubusercontent.com/106886638/196115966-4f377833-eb60-457e-8b1b-a782978b6c0f.png)
[latest.log](https://github.com/wisp-forest/owo-lib/files/9797937/latest.log)

Now some probably unnecessary information or fun facts:
It looks like this for the majority of the Mojang loading screen and the error is only visible for like a couple frames
![image](https://user-images.githubusercontent.com/106886638/196117420-a923026b-9d8e-49a2-9587-a3ed4da9f1c0.png)

Anyway, thank you for reading and hopefully finding the problem isn't that though? I unfortunately have no clue on how to find the problem, but probably anyone else can find it

**Comment by Noaaan** [comment] 2022-10-17 07:58
Font errors like that are usually a sign of DashLoader having issues. Have you tried running your game with it disabled?

**Comment by gliscowo** [comment] 2022-10-17 08:02
In fact, this is just what the text renderer does during a resource reload - it's missing every single glyph and thus always draws the empty box. I wouldn't be concerned about that, the actual owo error is significantly more strange, especially given the time at which it appears. The only way I could explain this is if someone is trying to initialize a config screen way too early, but we'll need to do some investigation - thanks for reporting
Cheers

**Comment by notIkibo** [comment] 2022-10-17 08:25
> Font errors like that are usually a sign of DashLoader having issues. Have you tried running your game with it disabled?

I just did and next to taking a minute longer to load, nothing changed

**Comment by notIkibo** [comment] 2022-10-17 08:32
> In fact, this is just what the text renderer does during a resource reload - it's missing every single glyph and thus always draws the empty box. I wouldn't be concerned about that, the actual owo error is significantly more strange, especially given the time at which it appears. The only way I could explain this is if someone is trying to initialize a config screen way too early, but we'll need to do some investigation - thanks for reporting Cheers

Wow, thanks mate. That is really good to hear. I do give out my issues, if I encounter any though most devs don't really care or don't trust it's their fault.
It surely is my mistake though then I need some basic understanding of modding and I don't know where to find that knowledge (except maybe a dozen of youtube videos)

**Comment by Firrae95** [comment] 2022-11-19 00:18
Has this issue been resolved? I have a minecraft server running and a few of the players on the server are reporting this same issue, already tried relogging into minecraft launcher and repairing profile in curseforge.

**Comment by notIkibo** [comment] 2022-11-19 09:43
No, unfortunately not. There hasn't been an update since I said that

**Comment by DontAtTheNex** [comment] 2023-04-29 06:17
I got something you can try, rollback to owo-lib-0.8.1+1.19.jar and if you have Fabric Waystones you may need to rollback that to wraith-waystones-3.0.3+mc1.19.2.jar and it _should_ boot up without any owo error.

This is just something I discovered when making my pack for MC 1.19.2 Fabric v0.14.19
Of course it maybe different depending on the mods you have but its worth a shot.

**Comment by splatchoot** [comment] 2023-06-04 17:14
i'm having this problem too, i know saying it won't fix your issue, but it might change the priority of this issue
it's also taking a looooooooooong time to load

**Comment by gliscowo** [comment] 2023-06-04 17:17
The reason why this hasn't been resolved yet isn't so much a lack of priority as it is simply the fact that nobody has been able to consistently reproduce it. Thus, if we can't reproduce the problem in a reliable manner, we can't try to figure out why it happens

If you think you can provide us with steps required in order to finally get it replicated reliably, please do let us know
Cheers

**Comment by notIkibo** [comment] 2023-06-04 20:35
Ngl, I don't have it anymore. It suddenly stopped occuring and I don't know when. Im on 1.19.2 on the latest update and latest Fabric Loader, but I think I already noticed it being gone in 19

**Comment by splatchoot** [comment] 2023-06-06 07:10
> If you think you can provide us with steps required in order to finally get it replicated reliably, please do let us know

It's a modpack I made with polymc, is there any way I can send you all the files of this modpack maybe?

**Comment by LevelsCraft7** [comment] 2023-06-24 23:58
Hello, I've also had this problem for some time, but for no real reason. 
I have identified this bug when Betterend mods and Macaws mods are active. I've deactivated everything that could be linked to UI in their configs, but to no avail. Has anyone found a solution?
Thanks

**Comment by PlayOrdinai** [comment] 2023-09-01 20:29
Hello, I may have the ability to reproduce it consistently on every launch via the modpack I am in development of, however from a chunk of trial and error I have not been able to resolve the issue, and the error is persistent. Is there an effective way I could try and help out with this issue being solved?

**Comment by gliscowo** [comment] 2024-12-12 00:35
As we have since added a mitigation (albeit not a root-cause fix) for this problem, I'll go ahead and close this issue

**Closed as completed by gliscowo** 2024-12-12 00:35 UTC
Labels: priority: low, status: confirmed, status: investigating, type: compatibility
