### ISSUE TITLE
Here is my log for my owo lib ui error

### ISSUE THREAD

**Issue by Noahfrechette** [wisp-forest/owo-lib#166] opened 2023-08-14 03:53 UTC
![aadasdasdasdasdadasdadasdas](https://github.com/wisp-forest/owo-lib/assets/73401157/4ea8ea98-6012-4707-b3fa-d97b77264b1b)
[latest.log](https://github.com/wisp-forest/owo-lib/files/12331358/latest.log)

**Comment by gliscowo** [comment] 2023-08-20 12:04
Is this error reproducible for you - as in, does it happen every time you launch the game with the mod list you were using? If not, I'm afraid this is a long standing problem and duplicate of #61 that we haven't been able to debug as we haven't found a way to reliably reproduce it

Cheers

**Comment by Assassingamer143** [comment] 2023-10-12 15:52
using the mod pack "Prominence II" this error pops up every time. Even removing the mod doesn't seem to work

**Comment by gliscowo** [comment] 2024-12-12 00:37
Closing as on #61

**Closed as completed by gliscowo** 2024-12-12 00:37 UTC
Labels: status: investigating, type: compatibility
