### ISSUE TITLE
Mixin inject failing causes a crash

### ISSUE THREAD

**Issue by cootshk** [wisp-forest/owo-lib#129] opened 2023-05-11 20:55 UTC
logs: https://mclo.gs/MvO2caI
crash report: https://mclo.gs/FcNtR7S

**Comment by Zailer43** [comment] 2023-05-15 01:02
Duplicate of #120

**Comment by gliscowo** [comment] 2023-05-19 09:33
As noted above, this is a duplicate of #120

**Closed as not planned by gliscowo** 2023-05-19 09:33 UTC
