### ISSUE TITLE
`drawChildren` can cause a null pointer exception if the component doesn't have a focus source

### ISSUE THREAD

**Issue by kikugie** [wisp-forest/owo-lib#289] opened 2024-08-23 09:56 UTC
`BaseComponent.drawChildren()` [gets the current focus handler](https://github.com/wisp-forest/owo-lib/blob/68b0aa6c590264ab5013340fe9af6e7d0421709d/src/main/java/io/wispforest/owo/ui/base/BaseParentComponent.java#L346) and [checks if the highlight should be drawn](https://github.com/wisp-forest/owo-lib/blob/68b0aa6c590264ab5013340fe9af6e7d0421709d/src/main/java/io/wispforest/owo/ui/base/BaseParentComponent.java#L355). However, `ParentComponent.focusHandler()` allows nullable return value, so calling `focusHandler.lastFocusSource()` can cause a `NullPointerException`.

So uh, insert a `if (focusHandler != null && ...)`

**Comment by gliscowo** [comment] 2024-08-23 10:38
While some extra assertions to clarify might certainly be of help, this is not a bug. 

The only circumstance under which a component returns a null focus handler is when it's not correctly mounted - in which state it also does not support being drawn.

May I inquire how you discovered this? Likely your component was not mounted, but if we can rule that out there might be a different bug somewhere 

Cheers

**Comment by gliscowo** [comment] 2024-09-15 11:43
If this issue is still of concern, please reopen it - I'll go ahead and close it for now
Cheers

**Closed as not planned by gliscowo** 2024-09-15 11:43 UTC
