### ISSUE TITLE
Alloy Forgery Crash?

### ISSUE THREAD

**Issue by ereese99** [wisp-forest/owo-lib#113] opened 2023-03-17 15:50 UTC
[message (1).txt](https://github.com/wisp-forest/owo-lib/files/11003143/message.1.txt)
Simply crashes when trying to access the alloy forgery

**Comment by Noaaan** [comment] 2023-03-17 16:23
Duplicate of https://github.com/wisp-forest/alloy-forgery/issues/80

**Closed as not planned** 2023-04-04 11:23 UTC
